name: Executar Script Manualmente Test3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

    strategy:
      matrix:
        index: [80, 81, 82, 83, 84]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar Dependências
        run: npm install

      - name: Executar Script
        run: |
          for i in ${{ matrix.index }}; do
            npm run start$i
          done
